### ISSUE TITLE
Please package using Angular Package Format

### ISSUE THREAD

**Issue by darbio** [erento/angular-api-client#11]
I get the following error when I build using `ng build --prod`.

```
ERROR in ./node_modules/ng2-api-client/src/apiClient.ts
Module build failed: Error: /Users/darbio/Repositories/da/ng-website/node_modules/ng2-api-client/src/apiClient.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/Users/darbio/Repositories/da/ng-website/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:656:23)
    at plugin.done.then (/Users/darbio/Repositories/da/ng-website/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 @ ./src/app/app.module.ngfactory.js 42:0-52
 @ ./src/main.ts
 @ multi ./src/main.ts
ERROR in ./node_modules/ng2-api-client/src/index.ts
Module build failed: Error: /Users/darbio/Repositories/da/ng-website/node_modules/ng2-api-client/src/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/Users/darbio/Repositories/da/ng-website/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:656:23)
    at plugin.done.then (/Users/darbio/Repositories/da/ng-website/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 @ ./src/app/app.module.ngfactory.js 82:0-48
 @ ./src/main.ts
 @ multi ./src/main.ts
ERROR in ./node_modules/ng2-api-client/src/url.builder.ts
Module build failed: Error: /Users/darbio/Repositories/da/ng-website/node_modules/ng2-api-client/src/url.builder.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/Users/darbio/Repositories/da/ng-website/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:656:23)
    at plugin.done.then (/Users/darbio/Repositories/da/ng-website/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 @ ./src/app/app.module.ngfactory.js 41:0-54
 @ ./src/main.ts
 @ multi ./src/main.ts
```

Changing my `tsconfig` to include `node_modules/ng2-api-client` fixes this, but the error suggests:

```
Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv)
```

TSConfig with workaround:
```
  "include": [
    "../src/**/*",
    "../node_modules/ng2-api-client/**/*"
  ],
```

**Comment by rokerkony** [comment]
Hi,
we are using ng-packager — it means we use the Angular Package Format.

Can you please maybe check if you are importing it in a right way?

e.g.:
```ts
import {ApiClientModule} from 'ng2-api-client';
```
everything should be imported from `ng2-api-client` (it looks you are using old version which not yet using ng-packager)
